### ISSUE TITLE
Error when the original file name are the same with the destination name

### ISSUE THREAD

**Issue by ghost** [jstolarek/dc-card-maker-script#2]
When the original name of the GDI/CDI file is "Disc" the line that i referenced below will throw an error and stop the process. I think this could be informed and later maybe check if the destination file (after the rename) is present and let the process continue. 

https://github.com/jstolarek/dc-card-maker-script/blob/3981aa9c43d0094e8a0edb42b986ed4c82c32f25/dc-card-maker.sh#L213

**Comment by jstolarek** [comment]
Good catch. Thanks! Fixed now.
