### ISSUE TITLE
settings not saving

### ISSUE THREAD

**Issue by ghost** [jstolarek/dc-card-maker-script#3]
hello, when changing the settings, logo and vga on off etc. it doesn't save the settings. I have a vmu in with 24 blocks of space but it never saves, is there a way to fix this? thanks

**Comment by jstolarek** [comment]
Sorry, but this isn't related in any way to this project. Saving the settings is provided by GDMenu itself, which dc-card-maker-script only builds upon.

**Comment by ghost** [comment]
@jstolarek I see, please do you have the actual save file you could send me which I could manually transfer to my VMU? as it isn't creating the save at all when pressing save settings
